### ISSUE TITLE
Rhino.Inside Revit support

### ISSUE THREAD

**Issue by michaldengusiak** [DanielAbalde/Sunglasses#12]
thanks for the amazing tool... however I am unable to load this when opening GH via Rhino.Inside Revit. I got it working in Rhino 6 and Rhino 7 but not when opening from Revit... any idea or suggestions?

GH from Revit
![image](https://user-images.githubusercontent.com/26113670/140059012-6102cc76-00da-46d7-a973-4eafd2617940.png)

GH from Rhino 7
![image](https://user-images.githubusercontent.com/26113670/140058874-a3221a42-a199-428d-bc17-bab8c7ca77af.png)

**Comment by DanielAbalde** [comment]
I don't know. Are you sure that InsideRevit is referencing the same GH plugin folder where Sunglasses.gha is? do you have more plugins installed? Or do you get some error message on Rhino?
