### ISSUE TITLE
Make available on Package Manager server?

### ISSUE THREAD

**Issue by Drodericson** [DanielAbalde/Sunglasses#17]
Hey, is there a possibility that you could publish this plugin to the Package Manager server? Not that it's difficult to install manually, but this would make the installation process for new users that are being introduced to grasshopper much more user-friendly!

https://developer.rhino3d.com/guides/yak/

**Comment by DanielAbalde** [comment]
Hey, thanks for the suggestion.

I have used YAK in the past but it gave me so many headaches upgrading plugins that I honestly don't feel like using it again for free plugins.
