### ISSUE TITLE
"Sketch" objects can't be excluded

### ISSUE THREAD

**Issue by fstwn** [DanielAbalde/Sunglasses#3]
Just noticed that it seems to be impossible to include drawn "Sketch" objects from sunglasses. Could someone have a look into this?

**Comment by DanielAbalde** [comment]
Eii @fstwn, sorry I didn't release this open issue until now. 

You are right, Sketchs are not handled by Sunglasses, for the moment it just catch all components and parameters.

 I don't think I need it but it could be an easy add for a next release.

**Comment by fstwn** [comment]
No problem! I would really appreciate it if excluding "Sketch" objects could be added. We use them for tutorial files for students quite frequently and with the annotation it tends to get a little messy.

Excluding "Scribble" objects works fine. I don't know the reason but that's nice!

If I find some time I'll dig in it myself, been wanting to look at the code of your beautiful plugin anyway :D
