### ISSUE TITLE
Font Picker crashes on Mac

### ISSUE THREAD

**Issue by DanielAbalde** [DanielAbalde/Sunglasses#4]
Reported by Andres Gonzalez, selecting Select Font on Mac, Rhino crashes.

See if it is an obsolete form or there is an ETO alternative... or check Rhino.Runtime.HostUtils.RunningOnWindows to add that menu item just for windows.

https://github.com/DanielAbalde/Sunglasses/blob/0b1d8ba7b9ca5c937601f8e40f6a171b58d0bbbe/MenuItem.cs#L71

**Comment by sbaer** [comment]
`CreateFontPickerWindow` is missing on Mac Rhino. We have this on our "todo" list to add, but I have no idea on when this would be done. It definitely won't be done for Rhino 6.
https://mcneel.myjetbrains.com/youtrack/issue/RH-63806

**Comment by DanielAbalde** [comment]
Replaced FontPicker by font size slider in Mac in v1.2.0
